### ISSUE TITLE
support line break with unused space delimiters language 

### ISSUE THREAD

**Issue by Modificator** [tdewolff/canvas#140]
some language unused  space delimiters 
like chinese 
```
哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈
哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈
哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈
```
like japanese
```
ハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハ
ハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハ
ハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハハッハッハ
```

Thanks

**Comment by tdewolff** [comment]
Support for East Asian line breaking isn't yet implemented. Currently the implemented Knuth's algorithms for line breaking works for Latin-like scripts. In order to support Chinese, Japanese, Korean, Thai, etc it would not be necessary to use Knuth's algorithms, but a simpler one could be used since we can break after most glyphs. In general, we need to adhere https://www.unicode.org/reports/tr14/ better. A simple set of rules can be found at https://en.wikipedia.org/wiki/Line_breaking_rules_in_East_Asian_languages

**Comment by tdewolff** [comment]
This should now be fixed. East Asian scripts (Han, Hangul, Katakana, Khmer, Lao, PhagsPa, Brahmi, TaiTham, NewTaiLue, TaiLe, TaiViet, Thai, Tibetan, Myanmar) can break between every glyph.

Additionally, I've added support for CFF CID fonts and for CFF2 fonts containing multiple fonts. This allows you to load the NotoCJK fonts for example!
