### ISSUE TITLE
[question] Adding func (t *Text) WalkLines to public API

### ISSUE THREAD

**Issue by orzel7** [tdewolff/canvas#216]
I am using canvas.Text to generate multi-line text to SVG. The question, is it possible to expose to public API functionality allowing to walk through lines of text. Something like func (t *Text) WalkLines(callback func(x, y float64, l Line)), where Line object contains all spans for a given Line. 
Obviously, my intention is to merge multiple spans sharing the same "y" coordinate into one SVG element.

**Comment by tdewolff** [comment]
Is your objective to compress the SVG output for each span? That is, merging the spans when the spacing is exactly one space? I would prefer to fix that regardless, instead of a quick fix on your end!

On the other hand, there is a `Text.WalkSpans` which does what you need but for each span. You'd need to group by `y` coordinate to get each line. The other idea is to expose the `line` struct and write a `Text.WalkLines` function as you mentioned.

**Comment by orzel7** [comment]
Yes, exactly. Currently I am using Text.WalkSpans, but I've found that "line" struct has all I need. Because I need only one font face per text block, generated output can be simplified. Additionally, it make possible usage of dy attribute to separate lines of text in SVG output.

**Comment by tdewolff** [comment]
I've exposed the `Text.WalkLines` function! But I think canvas should automatically create optimal SVG output when one font face is used per text block, and use the dy attribute. I will work on that!

**Comment by orzel7** [comment]
Thank you very much, I'will try this change.

Regarding SVG generation, I am using different approach. See  the fragment:
```svg
<g transform="translate(4 -4) rotate(-90)">
  <text font-size="1.5px" class="501" stroke="none">
    <tspan x="0" y="2.7078">Switching </tspan>
    <tspan x="6.7903" y="2.7078">input,</tspan>
    <tspan x="0" y="4.5183">vacuum </tspan>
    <tspan x="5.5994" y="4.5183">ON/OFF</tspan>
  </text>
</g>
```
Instead of applying transformation matrix and position to every separate "tspan" element, I'm using "g" element to apply transformation matrix once per text block.

**Comment by orzel7** [comment]
I've just checked it and realized, that span.x coordinate is not accessible because it private :-(

**Comment by tdewolff** [comment]
`TextSpan.X` is now exposed to public!

**Comment by tdewolff** [comment]
I've pushed out a fix to improve joining text spans when the spaces are not stretched, this makes the SVG output smaller. Next up we should use `transform="matrix(...)"` instead of the various transformation functions (`rotate`, `translate`, ...) when the matrix is smaller.

Additionally, I think we should add execution paths for when the text block has regular line spacing and uses only one font face, in which case we could get rid of the `tspans`. In case the `tspans` are necessary, perhaps omitting `x` when possible, or using `dx` and `dy` could further trim down the output size.

Anyways, I'm not sure what you mean by applying a transformation matrix for every `tspan` since that is not what is being outputted (nor what is allowed in the SVG spec). The transformation matrix is only set to the `text` object, adding a `<g>` tag around it only makes the output larger, isn't it?

**Comment by tdewolff** [comment]
Looking better at the SVG spec, it doesn't seem possible to specify linebreaks without `<tspan x="..."`, so I don't think we can further trim the size of the SVG output for text. If you have any ideas I'd be happy to hear them though! Please re-open the issue if you still have trouble.
