### ISSUE TITLE
How to import a PDF file from local storage?

### ISSUE THREAD

**Issue by ibryang** [tdewolff/canvas#278]
How to import a PDF file from local storage?

**Comment by tdewolff** [comment]
There is no way to parse a PDF file (yet). It is on the very future roadmap, but I don't intend to build a full PDF renderer (which is what it comes down to). I've only added basic SVG parsing support since it is a common format to describe vector paths. PDF not so much. Maybe there is a PDF parser in Go somewhere where you can iterate over shapes? Perhaps the PostScript data could be a candidate for parsing though...

**Comment by ibryang** [comment]
ok, thanks!
