### ISSUE TITLE
Trying to render go-charts into SVG with EmbedFonts=false generates empty file.

### ISSUE THREAD

**Issue by AlexanderMakarov** [tdewolff/canvas#307]
I need to render charts as SVG into Fyne. Direct rendering from https://github.com/wcharczuk/go-chart to Fyne causes issues in Fyne's underlying library github.com/srwiley/oksvg because it complains on go-chart's SVG output with line breaks and really strange looking.

So I decided to use this project ("canvas") as a translator between go-chart and Fyne. But next I've found that by-default "canvas" tries to embed fonts into SVG and Fyne's github.com/srwiley/oksvg started to complain on these base64 chunks of bytes.

I've found how to disable it, but suddenly found that it ends up with an empty file, without code at all. I use Linux Mint with Xfce.

Minimal repro code (need to "go get" relevant libs):

```
package main

import (
	"os"

	"github.com/tdewolff/canvas/renderers"
	"github.com/tdewolff/canvas/renderers/svg"
	"github.com/wcharczuk/go-chart/v2"
)

func main() {
	graph := chart.Chart{
		XAxis: chart.XAxis{
			Name: "The XAxis",
		},
		YAxis: chart.YAxis{
			Name: "The YAxis",
		},
		Series: []chart.Series{
			chart.ContinuousSeries{
				Style: chart.Style{
					StrokeColor: chart.GetDefaultColor(0).WithAlpha(64),
					FillColor:   chart.GetDefaultColor(0).WithAlpha(64),
				},
				XValues: []float64{1.0, 2.0, 3.0, 4.0, 5.0},
				YValues: []float64{1.0, 2.0, 3.0, 4.0, 5.0},
			},
		},
	}

	// Produces empty file.
	f, _ := os.Create("output.svg")
	defer f.Close()
	graph.Render(renderers.NewGoChart(renderers.SVG(renderers.SVG(svg.Options{
		EmbedFonts: false,
	}))), f)

	// Works OK.
	// f, _ := os.Create("output.svg")
	// defer f.Close()
	// graph.Render(chart.SVG, f)
}
```

**Comment by tdewolff** [comment]
The second case that works OK is when using the SVG renderer of go-chart. The problem isn't the fact that you use `EmbedFonts` but rather in how you use `renderers.SVG`. You should check the error that returns `graph.Render`, because it would've told you the problem: `unknown SVG option: canvas.Writer`. Which is maybe a bit cryptic, but you're nesting calls to `renderers.SVG`!

Correct code should be:
```go
f, _ := os.Create("output.svg")
defer f.Close()
err:= graph.Render(renderers.NewGoChart(renderers.SVG(&svg.Options{
	EmbedFonts: false,
})), f)
if err != nil {
	panic(err)
}
```

Additionally I've fixed some SVG rendering issues I came across. Please let me know how it goes!
