### ISSUE TITLE
DrawImage and opacity

### ISSUE THREAD

**Issue by tcurdt** [tdewolff/canvas#38]
I have a few hundred images that I am trying to combine, adding them with adjusted opacity. Just to clarify, along the lines of:

    for i:=0; i<100; i++ {
      img := createImage(i)
      ctx.DrawImage(0, 0, img, 10)
    }

Now, there are a couple of problems with this:

1. I would like to change the opacity when drawing the image. I assume I would have to do that beforehand to the image.RGBA? Not sure how yet - but there is no way to do this with `canvas`, correct?
2. It seems like drawing a lot of images is very resource hungry. Is there a way to optimize this? Or does it keep the images around and only combines them in the end?

**Comment by tdewolff** [comment]
1. Correct, you need to do this before passing to `canvas`. If `img` is an `image.RGBA`, you can use `Set(x, y int, c color.RGBA)` from https://golang.org/pkg/image/. Note that for RGBA, the alpha channel must be pre-multiplied to the colors. So red with 50% transparency would be `(127.5, 0, 0, 0.5)` and not `(255,0,0,0.5)`!
2. If you use `Canvas` as your drawing target then yes, it keeps all images around. If you use a specific renderer (such as the `rasterizer.Renderer`) then it will be drawn immediately to the final image. In general, drawing images isn't very fast, but maybe in `canvas` it wouldn't be necessary to run `draw,CatmullRom.Transform` if the transformation doesn't include rotations. This could be optimized.

**Comment by tcurdt** [comment]
Thanks for the clarificatoin.

I ended up doing the whole processing in the context of `image.RGBA`. Really not ideal - but otherwise it was just not remotely fast enough.

The fact that the images are kept around was a surprise. Maybe I just missed that in the docs? If not it would be nice to add that kind of information.

**Comment by tdewolff** [comment]
There are libraries for image manipulation in Go which could help you out, but in general I hadn't imaged canvas to provide such specialized support. Right now, it draws any image you pass it but there is no image manipulation code in Canvas.

The images are kept around because otherwise there'd be no way to generate multiple output file formats from on `Canvas`, i.e. exporting a PDF and a PNG of the same `Canvas`, we need to have all the information to build those documents. In the docs it is mentioned that `Canvas` is storing every draw action as layers, but I agree that documentation in general is a bit slim.
