### ISSUE TITLE
Why has the OpenGL module been commented out?

### ISSUE THREAD

**Issue by damien-lloyd** [tdewolff/canvas#39]
@tdewolff 

You made a commit on December 24th which commented out this file: https://github.com/tdewolff/canvas/blob/master/opengl.go

It's in the main branch, and there's still documentation and examples surrounding this module. What's the reason behind this commented out code?

Cheers,

**Comment by tdewolff** [comment]
Hey @damien-lloyd, mostly because it's not ready yet. Support for tesselation of all line types (line, bezier, arc) mostly. It's really a test example that is not ready for use yet. If you feel like it you could work on improving it bit by bit, but I guess you'd need to read the papers referenced first. Not sure what the timeline is either, I'm a bit busy as of late, but I value any input!

**Comment by tdewolff** [comment]
Going to close this issue as OpenGL will remain WIP.
