### ISSUE TITLE
multi-page pdfs

### ISSUE THREAD

**Issue by tcurdt** [tdewolff/canvas#51]
Is there a way a generating multi-page pdfs?

Right now I am generating the pages individually and then combine them later on.

**Comment by tdewolff** [comment]
Yes you can, I should include this in the `document` example. You have to do something along these lines:

```go
import "github.com/tdewolff/canvas/pdf"

w, err := os.Create(filename)
pdf := pdf.New(w, width, height)
defer pdf.Close()

ctx := canvas.NewContext(pdf)

// page one
ctx.DrawPath(...)

// page two
pdf.NewPage(width, height)
ctx.DrawPath(...)
```

Let me know if this works for you and whether you run into any problems.

**Comment by tcurdt** [comment]
...will the memory of previous pages be released with `NewPage`? or is the memory of all pages then bound to the single context? Just wondering about documents with many heavy pages.

**Comment by tdewolff** [comment]
When using PDF function as described above there will be nothing kept in memory as the context only keeps the current drawing state in memory (color of the pen etc.). So yes, no memory is kept not even between draw actions on one page. I think you were using `canvas.Canvas` previously which _does_ keep everything in memory so that it can later be written to any or multiple targets.

**Comment by tdewolff** [comment]
Assuming this is fixed, reopen if you still encounter issues!
