### ISSUE TITLE
how to use pixel sizes

### ISSUE THREAD

**Issue by peteraba** [tdewolff/canvas#52]
I noticed that if I create an SVG with a width of 2700, then I'll get a much wider image than 2700pixels. I assume it's because canvas uses DPMM instead of pixels. I have to wonder if it's possible to change or should I do the math on my side to compensate for it.

Thanks in advance!

**Comment by tdewolff** [comment]
You'll have to convert it yourself. In general, pixels are ill-defined for printable targets (PDF etc.) that's why vector graphics use device-independent measures such as inches or millimeters/centimeters. So it really depends on how many pixels (or dots) you think go into a millimeter, which surely depends on the DPI (or DPMM in our case). It seems however that SVG and CSS use a default of `1 millimeter = 96 / 25.4 pixel ≈ 3.78 pixel`, assuming DPI = 96.
