### ISSUE TITLE
Reduce the Renderer interface

### ISSUE THREAD

**Issue by oliverpool** [tdewolff/canvas#55]
Currently the `Renderer` interface has 4 methods (`Size`, `RenderPath`, `RenderText` and `RenderImage`).

Many renderers don't actually implement the `RenderText`, but fallback to rendering the text as path and calling `RenderPath`.

Instead of duplicating this "trick" everywhere, one could reduce the `Renderer` interface and introduce a `TextRenderer` interface (naming inspired from https://go.googlesource.com/proposal/+/master/design/draft-iofs.md#possible-future-or-third_party-extensions)

```go
// Renderer is an interface that renderers implement. It defines the size of the target (in mm) and functions to render paths, text objects and raster images.
// If the Renderer does not implement TextRenderer, the text will be converted to path.
type Renderer interface {
	Size() (float64, float64)
	RenderPath(path *Path, style Style, m Matrix)
	RenderImage(img image.Image, m Matrix)
}

// TextRenderer should be implemented to prevent text from being converted to path before rendering
type TextRenderer interface {
	Renderer
	RenderText(text *Text, m Matrix)
}
```

And then `context.DrawText` would use this method if available, or fallback to the `RenderPath` method:

```go
// DrawText draws text at position (x,y) using the current draw state. In particular, it only uses the current affine transformation matrix.
func (c *Context) DrawText(x, y float64, texts ...*Text) {
	m := c.view.Translate(x, y)
	for _, text := range texts {
		if text.Empty() {
			continue
		}
		renderText(c.Renderer, text, m)
	}
}

func renderText(r Renderer, text *Text, m Matrix) {
	t, ok := r.(TextRenderer)
	if ok {
		t.RenderText(text, m)
	} else {
		// transform text to path
		paths, colors := text.ToPaths()
		for i, path := range paths {
			style := DefaultStyle
			style.FillColor = colors[i]
			r.RenderPath(path, style, m)
		}
	}
}
```

Do you think this is a good idea? Would you be willing to accept a PR with those changes?

**Comment by tdewolff** [comment]
That is a pretty nice trick! It is true that the majority of the renderers defer to `RenderPath` for rendering text, but I think this is because most implementations are still minimal working examples. Overview:

- Rasterizer: defers, which is correct
- SVG: has its own implementation
- PDF: has its own implementations
- EPS: defers, but should be implemented in the future
- HTMLCanvas: defers, but should be implemented in the future
- TeX: defers, but should be implemented in the future?
- OpenGL (WIP): would defer probably

I think in general any renderer should implement a specialized `RenderText` in the end, so that adding this design complexity doesn't pay off that well. I think we could mitigate this partly by implementing `Text.RenderAsPath` (or similar) which would be the contents of the `RenderText` function that defers to `RenderPath`. Copying one line (or the current 5 lines) for a new renderer isn't such a big deal I think, especially if it keeps design relatively simple. It also makes renderer implementations conscious that the `RenderText` implementation is missing, which is really a required interface for a fully functioning renderer for `canvas`. I'd prefer not to encourage relying on paths instead of native text rendering.
