### ISSUE TITLE
Proposal : Draw behind, z index ?

### ISSUE THREAD

**Issue by kpym** [tdewolff/canvas#62]
I'm trying to draw a path behind. But it looks like the `RenderPath` can add only on top of the layers stack.

Is it possible to append a new method  `RenderPathBehind` ? Or even better add `z`-index parameter to the layers and when new path is added it is inserted at the right 'z'-position.

**Comment by tdewolff** [comment]
The interfaces for the specific target file formats are in "direct" mode, meaning that issuing a draw command immediately draws the path. The only exception is the general `Canvas` class, which keeps a record of layers to draw. We could add functionality there so that you can either set the Z-index for the next drawing commands, or set it explicitly for the current command. Thanks for the suggestion!

**Comment by kpym** [comment]
@tdewolff Thanks for the fast replay. But I don't get it : the canvas is file format independant no ? And the canvas [just stack](https://github.com/tdewolff/canvas/blob/22ab9a5a4f3ef1c41e48681819561144faa3fb43/canvas.go#L423) all the drawings in `layers`  ? So before to render the canvas to a particular format, we can reorder the layers, no ?

**Comment by kpym** [comment]
@tdewolff Thanks for your fast answer. Indeed I was talking about the general `Canvas`. By the way, I think that PDF has z-index capabilities.

**Comment by kpym** [comment]
I succeeded to draw white rectangle behind like this : 
```go
func onWhite(c *canvas.Canvas) *canvas.Canvas {
	cn := canvas.New(c.W, c.H)
	ctx := canvas.NewContext(cn)
	ctx.SetFillColor(canvas.White)
	ctx.DrawPath(0, 0, canvas.Rectangle(math.Ceil(c.W), math.Ceil(c.H)))
	c.Render(cn)

	return cn
}
```

But this is not very nice.

**Comment by tdewolff** [comment]
I've incorporated this issue in the new roadmap from where it will be tracked: #74
