### ISSUE TITLE
html-canvas ex busted

### ISSUE THREAD

**Issue by gedw99** [tdewolff/canvas#84]
develop branch.

```

cd canvas/examples/html-canvas && /Applications/Xcode.app/Contents/Developer/usr/bin/make build
GOARCH=wasm GOOS=js go build -o lib.wasm .
# github.com/tdewolff/canvas/htmlcanvas
../../htmlcanvas/htmlcanvas.go:130:19: not enough arguments in call to text.RenderAsPath
        have (*htmlCanvas, canvas.Matrix)
        want (canvas.Renderer, canvas.Matrix, canvas.Resolution)
make[1]: *** [build] Error 2
make: *** [ex-run-html] Error 2

```

**Comment by gedw99** [comment]
Feels like this project is at the point of needed github actions to exercise the examples ?

**Comment by tdewolff** [comment]
Thanks for the feedback, perhaps it would be useful to add GitHub actions, I agree. In the mean time, please run `git pull` or `go get -u github.com/tdewolff/canvas` as it seems you have an old version of canvas. This problem was from last week if I remember correctly ;-).

Please let me know if you have further problems!

**Comment by gedw99** [comment]
Yep master works - closing :)
